# Generated by Django 5.2.6 on 2025-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0003_alter_offer_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
