# Generated by Django 5.2.6 on 2025-09-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0004_alter_offer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
