# Generated by Django 5.2.6 on 2025-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0005_alter_offer_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.IntegerField(),
        ),
    ]
