# Generated by Django 5.2.6 on 2025-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0008_alter_offer_min_delivery_time_alter_offer_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="min_delivery_time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
