# Generated by Django 5.2.6 on 2025-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0009_alter_offer_min_delivery_time_alter_offer_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="min_delivery_time",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.FloatField(blank=True),
        ),
    ]
