# Generated by Django 5.2.6 on 2025-09-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0011_alter_offer_min_delivery_time_alter_offer_min_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="details",
        ),
        migrations.CreateModel(
            name="OfferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("revisons", models.IntegerField()),
                ("delivery_time_in_days", models.IntegerField()),
                ("price", models.FloatField()),
                ("features", models.JSONField(blank=True, null=True)),
                ("offer_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="app_offers.offer",
                    ),
                ),
            ],
        ),
    ]
