# Generated by Django 5.2.6 on 2025-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0012_remove_offer_details_offerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetails',
            old_name='revisons',
            new_name='revisions',
        ),
    ]
