# Generated by Django 5.2.6 on 2025-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0013_rename_revisons_offerdetails_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='price',
            field=models.IntegerField(),
        ),
    ]
