# Generated by Django 5.2.6 on 2025-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0014_alter_offerdetails_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="min_delivery_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="offerdetails",
            name="features",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="offerdetails",
            name="offer_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
