# Generated by Django 5.2.6 on 2025-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offers", "0020_alter_offer_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
