# Generated by Django 5.2.6 on 2025-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0021_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(default=0),
        ),
    ]
