# Generated by Django 5.2.6 on 2025-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0002_user_created_at_user_description_user_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="working_hours",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
