# Generated by Django 5.2.6 on 2025-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0003_alter_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(),
        ),
    ]
